// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Account struct {
	Address string  `json:"address"`
	PubKey  *string `json:"pubKey"`
	Num     int     `json:"num"`
	Seq     int     `json:"seq"`
	Coins   []Coin  `json:"coins"`
}

type Bot struct {
	Resource *Resource `json:"resource"`
	Name     string    `json:"name"`
	Dsinvite *string   `json:"dsinvite"`
}

type Coin struct {
	Denom  string `json:"denom"`
	Amount int    `json:"amount"`
}

type Link struct {
	ID         string  `json:"id"`
	Attributes *string `json:"attributes"`
}

type Owner struct {
	ID      *string `json:"id"`
	Address *string `json:"address"`
}

type Pseudonym struct {
	Resource *Resource `json:"resource"`
	Name     string    `json:"name"`
	Dsinvite *string   `json:"dsinvite"`
}

type Resource struct {
	ID               string  `json:"id"`
	Type             string  `json:"type"`
	Owner            Owner   `json:"owner"`
	SystemAttributes *string `json:"systemAttributes"`
	Attributes       *string `json:"attributes"`
	Links            []Link  `json:"links"`
}
