// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Account struct {
	Address  string  `json:"address"`
	PubKey   *string `json:"pubKey"`
	Number   BigUInt `json:"number"`
	Sequence BigUInt `json:"sequence"`
	Balance  []Coin  `json:"balance"`
}

type Bot struct {
	Record    *Record `json:"record"`
	Name      string  `json:"name"`
	AccessKey *string `json:"accessKey"`
}

type Coin struct {
	Type   string  `json:"type"`
	Amount BigUInt `json:"amount"`
}

type Record struct {
	ID         string  `json:"id"`
	Type       string  `json:"type"`
	Owner      string  `json:"owner"`
	Attributes *string `json:"attributes"`
}
